# Generated by Django 5.0 on 2024-01-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, upload_to='', verbose_name='تصویر'),
        ),
    ]
