# Generated by Django 5.0 on 2024-01-19 06:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.UUID('01b448b3-74da-4c30-87ee-3def449fdaca'), editable=False, primary_key=True, serialize=False)),
                ('PHONE', models.CharField(max_length=10)),
                ('receiver', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
