# Generated by Django 5.0 on 2024-01-23 13:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'مرد'), ('F', 'زن')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('61d38bc6-0145-4844-8504-61aa638f093f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
