# Generated by Django 5.0 on 2024-01-23 13:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_gender_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('7c681215-a987-41ea-bdd9-7f8585971f10'), editable=False, primary_key=True, serialize=False),
        ),
    ]
