# Generated by Django 5.0 on 2024-01-23 14:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('072198f1-bef9-4217-bf84-15d75e93c541'), editable=False, primary_key=True, serialize=False),
        ),
    ]
