# Generated by Django 5.0 on 2024-01-23 14:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('5ce8f660-4708-4182-9dd6-72ae463acf60'), editable=False, primary_key=True, serialize=False),
        ),
    ]
