# Generated by Django 5.0 on 2024-01-23 14:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('2d2a4694-bf2f-4712-b46a-379bc8f06449'), editable=False, primary_key=True, serialize=False),
        ),
    ]
