# Generated by Django 5.0 on 2024-01-24 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_user_options_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('c9e01bd7-3bee-4007-8795-f223281086f0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
