# Generated by Django 5.0 on 2024-01-24 07:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('23a61596-e829-492e-82fa-9bf81b8f3f37'), editable=False, primary_key=True, serialize=False),
        ),
    ]
