# Generated by Django 5.0 on 2024-01-24 07:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('627051da-2d7a-4a35-8c56-db5dec39cfa1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
