# Generated by Django 5.0 on 2024-01-24 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_otpcode_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPRequest',
        ),
    ]
