# Generated by Django 5.0 on 2024-01-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_delete_otprequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'مرد'), ('w', 'زن')], max_length=1, null=True),
        ),
    ]
