# Generated by Django 5.0 on 2024-02-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_otpcode_expiration_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
