# Generated by Django 5.0 on 2024-02-19 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_otpcode_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(choices=[('IT', 'کارشناس IT'), ('karamoz', 'کارآموز'), ('modir_markaz', 'مدیر مرکز'), ('moaven', 'معاون'), ('moshaver', 'مشاور'), ('morabi', 'مربی')], max_length=18)),
                ('thumbnail', models.ImageField(upload_to='images/', verbose_name='تصویر')),
                ('field', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='محتوا')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
