# Generated by Django 5.0 on 2024-01-05 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='نام دوره')),
                ('teacher', models.CharField(max_length=100, null=True, verbose_name='مدرس')),
                ('slug', models.SlugField(blank=True, default=None, unique=True, verbose_name='آدرس دوره')),
                ('thumbnail', models.ImageField(blank=True, default=None, upload_to='', verbose_name='تصویر')),
                ('description', models.TextField(verbose_name='محتوا')),
                ('time', models.IntegerField(verbose_name='مدت زمان دوره')),
                ('start', models.DateField(verbose_name='تاریخ شروع')),
                ('end', models.DateField(verbose_name='تاریخ پایان')),
                ('status', models.CharField(choices=[('n', 'شروع نشده است'), ('f', 'مهلت به پایان رسید')], max_length=1, verbose_name='وضعیت')),
                ('picture', models.ImageField(blank=True, default=None, upload_to='', verbose_name='تصویر مدرس')),
                ('govermentcenter', models.CharField(max_length=150, verbose_name='نام مرکز دولتی')),
                ('workshop', models.CharField(max_length=150, verbose_name='کارگاه/آموزشگاه')),
                ('gender', models.CharField(choices=[('w', 'مونث'), ('m', 'مذکر'), ('z', 'مونث ومذکر')], max_length=1, verbose_name='جنسیت')),
            ],
            options={
                'verbose_name': 'دوره',
                'verbose_name_plural': 'دوره ها',
            },
        ),
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Conect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='موضوع')),
                ('text', models.CharField(blank=True, max_length=700, null=True, verbose_name='متن پیام')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پیام ',
                'verbose_name_plural': 'پیام ها',
            },
        ),
        migrations.CreateModel(
            name='Choes_cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
            options={
                'unique_together': {('cours', 'user')},
            },
        ),
    ]
