# Generated by Django 5.0 on 2024-02-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
