# Generated by Django 5.0 on 2024-02-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='choes_cours',
            name='selection_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان انتخاب شده درس'),
        ),
    ]
