# Generated by Django 5.0 on 2024-02-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_choes_cours_selection_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choes_cours',
            name='selection_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='زمان انتخاب شده درس'),
        ),
    ]
