# Generated by Django 5.0 on 2024-02-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_free_school_options_free_school_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='conect',
            name='first_lastname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='conect',
            name='mehvar',
            field=models.CharField(blank=True, choices=[('ma', 'مالی'), ('ed', 'اداری'), ('am', 'آموزش'), ('sa', 'سنجش و گواهینامه'), ('ta', 'تکریم ارباب رجوع')], max_length=2, null=True, verbose_name='محور شکایت'),
        ),
        migrations.AddField(
            model_name='conect',
            name='national_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='conect',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='conect',
            name='subject',
            field=models.CharField(blank=True, choices=[('sh', 'شکایت'), ('da', 'درخوایت'), ('en', 'انتقاد')], max_length=2, null=True, verbose_name='موضوع'),
        ),
    ]
