# Generated by Django 5.0 on 2024-02-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_conect_first_lastname_conect_mehvar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conect',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
