# Generated by Django 5.0 on 2024-02-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_conect_national_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='conect',
            name='relationship',
            field=models.CharField(blank=True, choices=[('rm', 'رییس مرکز'), ('ka', 'کارشناس آموزش'), ('ki', 'کارشناس it'), ('ma', 'معاون آموزش'), ('em', 'ارتباط با مربیان')], max_length=2, null=True, verbose_name='ارتباط با'),
        ),
        migrations.AlterField(
            model_name='conect',
            name='subject',
            field=models.CharField(blank=True, choices=[('sh', 'شکایت'), ('da', 'درخواست'), ('en', 'انتقاد')], max_length=2, null=True, verbose_name='موضوع'),
        ),
    ]
