# Generated by Django 5.0 on 2024-02-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_conect_relationship_alter_conect_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='gender',
            field=models.CharField(choices=[('w', 'زن'), ('m', 'مرد'), ('wm', 'زن و مرد')], max_length=2, verbose_name='جنسیت'),
        ),
    ]
