# Generated by Django 5.0 on 2024-01-19 06:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='request_id',
            field=models.UUIDField(default=uuid.UUID('eaa7a4d7-c8ff-4478-a93c-fa709dbb9cab'), editable=False, primary_key=True, serialize=False),
        ),
    ]
